# docker-compose.yml

version: '1'
services:
  db:
    image: "postgres:16.0-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_development

  # app:
  #   image: node:10.12.0
  #   working_dir: /books
  #   entrypoint: ["/bin/bash", "./entrypoint.sh"]
    
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/restify-pg
  #   environment:
  #     DB_HOST: db
